import {classifyShot,summarize} from './scoring.js';
import {projectAim} from './aim-model.js';
const $=id=>document.getElementById(id),arena=$('arena'),targetEl=$('target'),crosshair=$('crosshair'),overlay=$('overlay'),results=$('results');
const state={phase:'ready',remaining:120000,lastTick:0,aim:{x:0,y:0},angle:{x:0,y:0},target:null,shots:[],settings:null,id:0,calibration:null,calibrationMovement:0};
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
const showEdpi=()=>{$('edpi').textContent=`eDPI: ${(Number($('dpi').value)*Number($('sensitivity').value)).toFixed(2)}`};
$('dpi').addEventListener('input',showEdpi);$('sensitivity').addEventListener('input',showEdpi);showEdpi();
const place=(el,p)=>{el.style.left=`${p.x}px`;el.style.top=`${p.y}px`};
const message=(heading,body)=>{$('overlay-title').textContent=heading;$('overlay-detail').textContent=body;overlay.hidden=false};
function hud(){const sec=Math.ceil(state.remaining/1000);$('timer').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;$('score').textContent=`${state.shots.length} shots · ${state.shots.filter(s=>s.outcome==='hit').length} hits`;$('status').textContent=state.phase==='active'?'Aim and click':state.phase==='paused'?'Paused':state.phase==='complete'?'Complete':state.phase==='calibrating'?'Move 10 cm right, then click':'Ready'}
function spawn(){const w=arena.clientWidth,h=arena.clientHeight;state.angle={x:0,y:0};state.aim={x:w/2,y:h/2};place(crosshair,state.aim);const pad=Math.min(36,w/4,h/4);let p;for(let i=0;i<30;i++){p={x:pad+Math.random()*(w-2*pad),y:pad+Math.random()*(h-2*pad)};if(Math.hypot(p.x-state.aim.x,p.y-state.aim.y)>=Math.min(120,w*.3))break}state.target={id:++state.id,...p,origin:{...state.aim},startedAt:performance.now(),path:[]};place(targetEl,p);targetEl.hidden=false}
function pause(body='Click the arena to lock the mouse and continue.'){if(state.phase!=='active')return;state.phase='paused';state.lastTick=0;if(document.pointerLockElement===arena)document.exitPointerLock();message('Round paused',body);hud()}
function finish(){if(state.phase==='complete')return;state.phase='complete';state.remaining=0;state.target=null;targetEl.hidden=true;crosshair.hidden=true;message('Round complete','Review your shot patterns below. Start another round to compare.');if(document.pointerLockElement===arena)document.exitPointerLock();const r=summarize(state.shots);results.hidden=false;results.replaceChildren();const heading=document.createElement('h2');heading.textContent='Round summary';results.append(heading);const grid=document.createElement('div');grid.className='stats';for(const [label,value] of [['Shots',r.shots],['Hits',r.hits],['Accuracy',`${r.accuracy}%`],['Overshoots',r.overshoots],['Undershoots',r.undershoots],['Other misses',r.otherMisses],['Mouse movement',`${Math.round(r.pathLength)} counts`]]){const item=document.createElement('div'),name=document.createElement('span'),number=document.createElement('strong');name.textContent=label;number.textContent=value;item.append(name,number);grid.append(item)}results.append(grid);const note=document.createElement('p');note.className='muted note';note.textContent=`Recorded at ${state.settings.dpi} DPI and Valorant sensitivity ${state.settings.sensitivity}. Overshoot means the aim passed the target before a miss; undershoot means it stopped short. Calibrated with ${state.settings.cm360} cm/360, ${state.settings.fovDegrees}° horizontal FOV, and ${state.settings.movementUnitsPerCm.toFixed(1)} browser units/cm. Compare rounds on the same browser, mouse and DPI. This is an approximation, not a verified Valorant input clone.`;results.append(note);const table=document.createElement('table');table.style.cssText='width:100%;margin-top:18px;border-collapse:collapse;text-align:left;font-variant-numeric:tabular-nums';const header=document.createElement('tr');for(const label of ['Shot','Result','Error (px)','Time (ms)','Target → shot (px)']){const cell=document.createElement('th');cell.textContent=label;cell.style.padding='8px';header.append(cell)}table.append(header);for(const shot of state.shots){const row=document.createElement('tr');for(const value of [shot.targetId,shot.outcome,Math.round(shot.errorPx),Math.round(shot.durationMs),`(${Math.round(shot.target.x)}, ${Math.round(shot.target.y)}) → (${Math.round(shot.shot.x)}, ${Math.round(shot.shot.y)})`]){const cell=document.createElement('td');cell.textContent=value;cell.style.cssText='padding:8px;border-top:1px solid #35445a';row.append(cell)}table.append(row)}const scroll=document.createElement('div');scroll.style.overflowX='auto';scroll.append(table);results.append(scroll);hud()}
function tick(now){if(state.phase==='active'){if(state.lastTick)state.remaining=Math.max(0,state.remaining-(now-state.lastTick));state.lastTick=now;if(!state.remaining)finish();hud()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
$('calibrate').addEventListener('click',()=>{if(document.pointerLockElement===arena)document.exitPointerLock();state.phase='calibrating';state.calibration=null;state.calibrationMovement=0;message('Calibrate a 10 cm sweep','Click the arena to lock, move your mouse exactly 10 cm to the right, then click again. Do not lift or reverse the mouse.');hud()});
$('start').addEventListener('click',()=>{const dpi=Number($('dpi').value),sensitivity=Number($('sensitivity').value),cm360=Number($('cm360').value),fovDegrees=Number($('fov').value);if(!$('dpi').value||!$('sensitivity').value||!Number.isFinite(dpi)||dpi<100||dpi>30000||!Number.isFinite(sensitivity)||sensitivity<.001||sensitivity>10||!$('cm360').value||!Number.isFinite(cm360)||cm360<1||cm360>200||!Number.isFinite(fovDegrees)||fovDegrees<30||fovDegrees>150||!state.calibration||state.calibration.dpi!==dpi){message('Calibration required','Enter your measured Valorant cm/360 and a horizontal FOV, then calibrate a 10 cm browser sweep at the current DPI.');return}if(document.pointerLockElement===arena)document.exitPointerLock();Object.assign(state,{phase:'paused',remaining:120000,lastTick:0,shots:[],id:0,settings:{dpi,sensitivity,cm360,cmPer360:cm360,fovDegrees,movementUnitsPerCm:state.calibration.movementUnitsPerCm}});state.aim={x:arena.clientWidth/2,y:arena.clientHeight/2};place(crosshair,state.aim);crosshair.hidden=false;results.hidden=true;spawn();message('Click to lock mouse','The timer starts when pointer lock is acquired. Esc pauses.');hud()});
// Clicks that acquire pointer lock never fire. Only clicks while already locked count as shots.
arena.addEventListener('click',async e=>{if(e.button!==0||state.phase==='ready'||state.phase==='complete')return;if(document.pointerLockElement!==arena){try{await arena.requestPointerLock({unadjustedMovement:true})}catch{try{await arena.requestPointerLock()}catch{message('Mouse lock failed','Allow pointer lock in the browser, then click again.')}}return}if(state.phase==='calibrating'){const units=Math.abs(state.calibrationMovement);if(units<20){message('Sweep too short','Move 10 cm to the right before clicking to finish calibration.');return}state.calibration={dpi:Number($('dpi').value),movementUnitsPerCm:units/10};state.phase='ready';document.exitPointerLock();message('Browser sweep saved',`${(units/10).toFixed(1)} browser movement units per cm. Enter measured Valorant cm/360, then start the round.`);hud();return}if(state.phase!=='active'||!state.target)return;const t=state.target;const shot={targetId:t.id,target:{x:t.x,y:t.y},origin:t.origin,shot:{...state.aim},durationMs:performance.now()-t.startedAt,path:t.path};Object.assign(shot,classifyShot(shot));state.shots.push(shot);spawn();hud()});
arena.addEventListener('mousemove',e=>{if(document.pointerLockElement!==arena)return;if(state.phase==='calibrating'){state.calibrationMovement+=e.movementX;return}if(state.phase!=='active')return;const projected=projectAim(state.angle,{dx:e.movementX,dy:e.movementY},{width:arena.clientWidth,height:arena.clientHeight,...state.settings});state.angle=projected.angle;state.aim={x:projected.x,y:projected.y};place(crosshair,state.aim);state.target.path.push({t:performance.now()-state.target.startedAt,dx:e.movementX,dy:e.movementY,x:state.aim.x,y:state.aim.y})});
document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===arena;arena.classList.toggle('locked',locked);if(locked&&state.phase==='calibrating'){overlay.hidden=true;hud()}else if(locked&&state.phase==='paused'){state.phase='active';state.lastTick=0;if(state.target)state.target.startedAt=performance.now();overlay.hidden=true;hud()}else if(!locked){if(state.phase==='calibrating'){state.calibrationMovement=0;message('Calibration interrupted','Click the arena and repeat the 10 cm sweep.')}else pause()}});document.addEventListener('pointerlockerror',()=>pause('Pointer lock was denied. Check browser permissions and click again.'));window.addEventListener('blur',()=>pause('Return to this tab and click the arena to continue.'));
window.addEventListener('resize',()=>{const w=arena.clientWidth,h=arena.clientHeight;state.aim.x=clamp(state.aim.x,0,w);state.aim.y=clamp(state.aim.y,0,h);place(crosshair,state.aim);if(state.target){state.target.x=clamp(state.target.x,20,w-20);state.target.y=clamp(state.target.y,20,h-20);place(targetEl,state.target)}if(state.phase==='active'){pause('Arena size changed. The unfinished target was reset. Click to continue.');spawn()}});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await arena.requestFullscreen()}catch{$('status').textContent='Fullscreen unavailable'}});document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit fullscreen':'Fullscreen'});
